import { ResourceType, ec2SecurityGroupRules, ecsTaskDefinitionFamily } from "./ResourceType.js";

export type ResourceTypeDependencies = Record<ResourceType, ResourceType[]>;

export const resourceTypeDependencies: ResourceTypeDependencies = {
  "cloudfront.distribution": [],
  "cloudwatch.alarm": [],
  "dynamodb.table": [],
  "ec2.elastic-ip": ["ec2.vpc"],
  "ec2.instance": ["ec2.elastic-ip", "ec2.launch-template", "ec2.security-group", "ec2.subnet"],
  "ec2.internet-gateway": ["ec2.elastic-ip"],
  "ec2.launch-template": [],
  "ec2.natgateway": ["ec2.elastic-ip", "ec2.internet-gateway", "ec2.subnet"],
  "ec2.network-interface": [],
  "ec2.route-table": ["ec2.internet-gateway", "ec2.vpc"],
  "ec2.security-group": ["ec2.vpc"],
  [ec2SecurityGroupRules]: ["ec2.security-group"],
  "ec2.subnet": ["ec2.vpc"],
  "ec2.vpc-endpoint": ["ec2.vpc"],
  "ec2.vpc-flow-log": ["logs.log-group"],
  "ec2.vpc": [],
  "ecr.repository": [],
  "ecs.capacity-provider": [],
  "ecs.cluster": ["ecs.capacity-provider"],
  "ecs.container-instance": [],
  "ecs.service": [
    "ec2.elastic-ip",
    "ec2.internet-gateway",
    "ec2.security-group",
    "ec2.subnet",
    "ecs.cluster",
    "ecs.container-instance",
    "ecs.task",
    "ecs.task-definition",
    "servicediscovery.service",
  ],
  "ecs.task": [
    "ec2.elastic-ip",
    "ec2.internet-gateway",
    "ec2.security-group",
    "ec2.subnet",
    "ecs.cluster",
    "ecs.container-instance",
    "ecs.task-definition",
  ],
  "ecs.task-definition": [ecsTaskDefinitionFamily, "iam.role", "logs.log-group"],
  [ecsTaskDefinitionFamily]: [],
  "elasticache.cluster": [
    "ec2.internet-gateway",
    "ec2.security-group",
    "elasticache.parametergroup",
    "elasticache.replicationgroup",
    "elasticache.snapshot",
    "elasticache.subnetgroup",
  ],
  "elasticache.parametergroup": [],
  "elasticache.replicationgroup": [
    "ec2.internet-gateway",
    "ec2.security-group",
    "elasticache.parametergroup",
    "elasticache.snapshot",
    "elasticache.subnetgroup",
  ],
  "elasticache.snapshot": [],
  "elasticache.subnetgroup": ["ec2.subnet"],
  "elasticloadbalancing.listener-rule": ["elasticloadbalancing.listener"],
  "elasticloadbalancing.listener": ["elasticloadbalancing.loadbalancer", "elasticloadbalancing.targetgroup"],
  "elasticloadbalancing.loadbalancer": [
    "ec2.elastic-ip",
    "ec2.internet-gateway",
    "ec2.security-group",
    "ec2.subnet",
    "s3",
  ],
  "elasticloadbalancing.targetgroup": ["ec2.vpc"],
  "events.rule": [],
  "firehose.deliverystream": [],
  "geo.place-index": [],
  "iam.instance-profile": ["iam.role"],
  "iam.policy": [],
  "iam.role": ["iam.policy"],
  "kafka.cluster": ["ec2.security-group", "ec2.subnet", "iam.role", "logs.log-group"],
  "kms.key": [],
  "logs.log-group": [],
  "rds.cluster-pg": [],
  "rds.cluster-snapshot": [],
  "rds.cluster": [
    "ec2.internet-gateway",
    "ec2.security-group",
    "iam.role",
    "logs.log-group",
    "rds.cluster-pg",
    "rds.cluster-snapshot",
    "rds.subgrp",
  ],
  "rds.db": ["ec2.internet-gateway", "ec2.security-group", "logs.log-group", "rds.cluster", "rds.subgrp"],
  "rds.subgrp": ["ec2.subnet"],
  "route53.hostedzone": [],
  s3: ["iam.policy"],
  "secretsmanager.secret": [],
  "servicediscovery.namespace": [],
  "servicediscovery.service": ["servicediscovery.namespace"],
  sns: [],
  "ssm.parameter": [],
};
